'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    navbar_home: 'Home',
    navbar_chat: 'AI Advisor',
    navbar_dashboard: 'My Permits',
    navbar_get_started: 'Get Started',
    home_hero_title: 'Building Turkey, Together.',
    home_hero_subtitle: 'The fastest path to your Turkish business permits. AI-powered, government-aligned, and ready for launch.',
    home_hero_greeting_user: 'Hi Hamza',
    home_hero_question: 'Where should we start?',
    home_hero_cta: 'Get Started',
    hero_cat_upload: 'Upload documents',
    hero_cat_status: 'Check status',
    hero_cat_protocols: 'Beşiktaş protocols',
    hero_cat_safety: 'Fire safety guide',
    how_it_works_label: 'How it works',
    process_title: 'The Process',
    process_subtitle: "Getting permits shouldn't be a mystery.",
    process_step1_title: '1. Describe',
    process_step1_desc: 'Enter your business type or permit requirement in plain Turkish or English. Our AI understands municipal nuance.',
    process_step2_title: '2. Analyze',
    process_step2_desc: 'PermitOps AI cross-references 450+ municipal protocols to determine your exact path and required files.',
    process_step3_title: '3. Automate',
    process_step3_desc: 'Our RPA bot handles the heavy lifting on e-Devlet, filling forms and tracking status while you focus on business.',
    dashboard_title: 'Permit Dashboard',
    dashboard_sync: 'Sync',
    dashboard_ask_ai: 'Ask AI',
    dashboard_upload: 'Upload Docs',
    chat_placeholder: 'Ask PermitOps AI...',
    chat_new: 'New Chat',
    chat_greeting: 'Hello there.',
    chat_subtitle: 'How can I help with Istanbul permits today?',
    chat_q1: 'What permits do I need for a restaurant in Istanbul?',
    chat_q2: 'How long does the fire safety inspection take?',
    chat_q3: 'What documents does Beşiktaş Municipality require?',
    chat_q4: 'What is the cost of a fire safety certificate?',
    dashboard_updated: 'Updated',
    dashboard_live_session: 'Live Session',
    dashboard_days: 'days',
    dashboard_active: 'active',
    dashboard_running: 'Running',
    dashboard_agent_status: 'Agent processing workflow',
    dashboard_ask_ai_step: 'Ask AI about this step',
    dashboard_no_session: 'No active session',
    dashboard_processing: 'Processing...',
    dashboard_compliance_score: 'Compliance Score',
    dashboard_steps_complete: 'Steps Complete',
    dashboard_est_days: 'Est. Days Left',
    dashboard_active_agents: 'Active AI Agents',
    dashboard_overall_progress: 'Overall Progress',
    dashboard_workflow_steps: 'Workflow Steps',
    dashboard_action_required: 'Action Required',
    dashboard_all_clear: 'All clear',
    dashboard_action_required_desc: 'Please complete the {step} step to proceed.',
    dashboard_bot_processing: 'System is currently processing agent tasks.',
    dashboard_whats_next: 'What\'s next',
    dashboard_next_step_desc: 'After the fire certificate is submitted, your İşyeri Açma ve Çalışma Ruhsatı will be requested automatically.',
    dashboard_init_title: 'Initialize Workflow',
    dashboard_init_summary: 'Start a chat to generate your permit plan.',
    dashboard_init_detail: 'Once you describe your business in the chat, the AI will generate a customized permit path for you here.',
    dashboard_mark_complete: 'Mark as Complete',
    dashboard_mark_done: 'Mark step as done',
    dashboard_syncing: 'Synchronizing with Beşiktaş Municipality...',
    dashboard_toast_success: 'Document uploaded successfully!',
    dashboard_auto_execute: 'Auto-Execute Bot',
    status_completed: 'Completed',
    status_in_progress: 'In Progress',
    status_pending: 'Pending',
    chat_welcome: 'Hi {name}',
    chat_begin: 'Where do we begin?',
    chat_placeholder_alt: 'Ask Gemini 3...',
    chat_suggestion_business: 'What business you want to open?',
    chat_suggestion_permit: 'What permit do you want?',
    chat_suggestion_location: 'Where is your business located?',
    chat_suggestion_duration: 'How long does it take?',
    chat_suggestion_cost: 'How much does it cost?',
    chat_suggestion_obtain: 'I want to obtain a business permit',
    chat_suggestion_steps: 'I want to know the steps',
    chat_suggestion_docs: 'What documents do I need?',
    chat_suggestion_help: 'How does it work?',
    sidebar_new_chat: 'New Chat',
    sidebar_recent: 'Recent',
    sidebar_help: 'Help',
    sidebar_activity: 'Activity',
    sidebar_settings: 'Settings',
  },
  tr: {
    navbar_home: 'Ana Sayfa',
    navbar_chat: 'Yapay Zeka Danışmanı',
    navbar_dashboard: 'İzinlerim',
    navbar_get_started: 'Başla',
    home_hero_title: 'Türkiye\'yi Birlikte İnşa Ediyoruz.',
    home_hero_subtitle: 'İş yeri açma ruhsatınıza giden en hızlı yol. Yapay zeka destekli, resmi makamlarla uyumlu.',
    home_hero_greeting_user: 'Selam Hamza',
    home_hero_question: 'Nereden başlayalım?',
    home_hero_cta: 'Başla',
    hero_cat_upload: 'Belge yükle',
    hero_cat_status: 'Durumu kontrol et',
    hero_cat_protocols: 'Beşiktaş protokolleri',
    hero_cat_safety: 'Yangın güvenliği rehberi',
    how_it_works_label: 'Nasıl çalışır',
    process_title: 'Süreç',
    process_subtitle: 'Ruhsat almak bir gizem olmamalı.',
    process_step1_title: '1. Tarif Et',
    process_step1_desc: 'İş türünüzü veya izin gereksiniminizi Türkçe veya İngilizce olarak belirtin. Yapay zekamız belediye mevzuatlarını anlar.',
    process_step2_title: '2. Analiz Et',
    process_step2_desc: 'PermitOps AI, tam yolunuzu ve gerekli dosyaları belirlemek için 450+ belediye protokolünü tarar.',
    process_step3_title: '3. Otomatize Et',
    process_step3_desc: 'RPA botumuz e-Devlet üzerindeki ağır işleri halleder, formları doldurur ve durumu sizin yerinize takip eder.',
    dashboard_title: 'İzin Paneli',
    dashboard_sync: 'Senkronize Et',
    dashboard_ask_ai: 'AI\'ya Sor',
    dashboard_upload: 'Belge Yükle',
    chat_placeholder: 'PermitOps AI\'ya sor...',
    chat_new: 'Yeni Sohbet',
    chat_greeting: 'Selam.',
    chat_subtitle: 'Bugün İstanbul izinleri konusunda nasıl yardımcı olabilirim?',
    chat_q1: 'İstanbul\'da restorant için hangi izinlere ihtiyacım var?',
    chat_q2: 'Yangın güvenliği denetimi ne kadar sürer?',
    chat_q3: 'Beşiktaş Belediyesi hangi belgeleri istiyor?',
    chat_q4: 'Yangın güvenlik sertifikasının maliyeti nedir?',
    dashboard_updated: 'Güncellendi',
    dashboard_live_session: 'Canlı Oturum',
    dashboard_days: 'gün',
    dashboard_active: 'aktif',
    dashboard_running: 'Çalışıyor',
    dashboard_agent_status: 'Ajan iş akışını işliyor',
    dashboard_ask_ai_step: 'Bu adım hakkında AI\'ya sor',
    dashboard_no_session: 'Aktif oturum yok',
    dashboard_processing: 'İşleniyor...',
    dashboard_compliance_score: 'Uyum Skoru',
    dashboard_auto_execute: 'Botu Otomatik Çalıştır',
    dashboard_steps_complete: 'Tamamlanan Adımlar',
    dashboard_est_days: 'Tahmini Kalan Gün',
    dashboard_active_agents: 'Aktif AI Ajanları',
    dashboard_overall_progress: 'Genel İlerleme',
    dashboard_workflow_steps: 'İş Akışı Adımları',
    dashboard_action_required: 'Eylem Gerekiyor',
    dashboard_all_clear: 'Her şey yolunda',
    dashboard_action_required_desc: 'Lütfen devam etmek için {step} adımını tamamlayın.',
    dashboard_bot_processing: 'Sistem şu anda ajan görevlerini işliyor.',
    dashboard_whats_next: 'Sıradaki ne?',
    dashboard_next_step_desc: 'Yangın belgesi teslim edildikten sonra İşyeri Açma ve Çalışma Ruhsatınız otomatik olarak talep edilecektir.',
    dashboard_init_title: 'İş Akışını Başlat',
    dashboard_init_summary: 'İzin planınızı oluşturmak için bir sohbet başlatın.',
    dashboard_init_detail: 'Sohbet kısmında işinizi tarif ettiğinizde, yapay zeka size özel izin yolunu burada oluşturacaktır.',
    dashboard_mark_complete: 'Tamamlandı Olarak İşaretle',
    dashboard_mark_done: 'Adımı tamamlandı işaretle',
    dashboard_syncing: 'Beşiktaş Belediyesi ile senkronize ediliyor...',
    dashboard_toast_success: 'Belge başarıyla yüklendi!',
    status_completed: 'Tamamlandı',
    status_in_progress: 'Devam Ediyor',
    status_pending: 'Beklemede',
    chat_welcome: 'Selam {name}',
    chat_begin: 'Nereden başlayalım?',
    chat_placeholder_alt: 'Gemini 3\'e sorun...',
    chat_suggestion_business: 'Hangi işi açmak istiyorsunuz?',
    chat_suggestion_permit: 'Hangi izni istiyorsunuz?',
    chat_suggestion_location: 'İşletmeniz nerede?',
    chat_suggestion_duration: 'Ne kadar sürer?',
    chat_suggestion_cost: 'Maliyeti nedir?',
    chat_suggestion_obtain: 'İş yeri açma ruhsatı almak istiyorum',
    chat_suggestion_steps: 'Adımları öğrenmek istiyorum',
    chat_suggestion_docs: 'Hangi belgelere ihtiyacım var?',
    chat_suggestion_help: 'Nasıl çalışır?',
    sidebar_new_chat: 'Yeni Sohbet',
    sidebar_recent: 'Geçmiş',
    sidebar_help: 'Yardım',
    sidebar_activity: 'Etkinlik',
    sidebar_settings: 'Ayarlar',
  },
  ar: {
    navbar_home: 'الرئيسية',
    navbar_chat: 'مستشار الذكاء الاصطناعي',
    navbar_dashboard: 'تصاريحي',
    navbar_get_started: 'ابدأ الآن',
    home_hero_title: 'نبني تركيا معاً.',
    home_hero_subtitle: 'أسرع طريق للحصول على تصاريح عملك في تركيا. مدعوم بالذكاء الاصطناعي ومتوافق مع الجهات الحكومية.',
    home_hero_greeting_user: 'أهلاً حمزة',
    home_hero_question: 'من أين نبدأ؟',
    home_hero_cta: 'ابدأ الآن',
    hero_cat_upload: 'رفع المستندات',
    hero_cat_status: 'تحقق من الحالة',
    hero_cat_protocols: 'بروتوكولات بشكتاش',
    hero_cat_safety: 'دليل السلامة من الحرائق',
    how_it_works_label: 'كيف يعمل',
    process_title: 'العملية',
    process_subtitle: 'لا ينبغي أن يكون الحصول على التصاريح لغزاً.',
    process_step1_title: '١. صف عملك',
    process_step1_desc: 'أدخل نوع عملك أو متطلبات التصريح باللغة التركية أو الإنجليزية أو العربية. يفهم الذكاء الاصطناعي لدينا الفروق التابعة للبلديات.',
    process_step2_title: '٢. التحليل',
    process_step2_desc: 'يقوم PermitOps AI بمراجعة أكثر من ٤٥٠ بروتوكولاً بلدياً لتحديد مسارك الدقيق والملفات المطلوبة.',
    process_step3_title: '٣. الأتمتة',
    process_step3_desc: 'يقوم بوت RPA الخاص بنا بالمهام الصعبة على e-Devlet، حيث يملأ النماذج ويتتبع الحالة بينما تركز أنت على عملك.',
    dashboard_title: 'لوحة التحكم',
    dashboard_sync: 'مزامنة',
    dashboard_ask_ai: 'اسأل الذكاء الاصطناعي',
    dashboard_upload: 'رفع المستندات',
    chat_placeholder: 'اسأل PermitOps AI...',
    chat_new: 'دردشة جديدة',
    chat_greeting: 'أهلاً بك.',
    chat_subtitle: 'كيف يمكنني مساعدتك في تصاريح إسطنبول اليوم؟',
    chat_q1: 'ما هي التصاريح التي أحتاجها لمطعم في إسطنبول؟',
    chat_q2: 'كم يستغرق فحص السلامة من الحرائق؟',
    chat_q3: 'ما هي المستندات التي تطلبها بلدية بشكتاش؟',
    chat_q4: 'ما هي تكلفة شهادة السلامة من الحرائق؟',
    dashboard_updated: 'تم التحديث',
    dashboard_live_session: 'جلسة مباشرة',
    dashboard_days: 'أيام',
    dashboard_active: 'نشط',
    dashboard_running: 'يعمل',
    dashboard_agent_status: 'الوكيل يعالج سير العمل',
    dashboard_ask_ai_step: 'اسأل الذكاء الاصطناعي عن هذه الخطوة',
    dashboard_no_session: 'لا توجد جلسة نشطة',
    dashboard_processing: 'جاري المعالجة...',
    dashboard_compliance_score: 'درجة الامتثال',
    dashboard_steps_complete: 'الخطوات المكتملة',
    dashboard_est_days: 'الأيام المتبقية المتوقعة',
    dashboard_active_agents: 'وكلاء الذكاء الاصطناعي النشطون',
    dashboard_overall_progress: 'التقدم العام',
    dashboard_workflow_steps: 'خطوات سير العمل',
    dashboard_action_required: 'إجراء مطلوب',
    dashboard_all_clear: 'كل شيء جاهز',
    dashboard_action_required_desc: 'يرجى إكمال خطوة {step} للمتابعة.',
    dashboard_bot_processing: 'يقوم النظام حاليًا بمعالجة مهام الوكيل.',
    dashboard_whats_next: 'ماذا بعد؟',
    dashboard_next_step_desc: 'بعد تقديم شهادة الحريق، سيتم طلب رخصة فتح وممارسة العمل (İşyeri Açma ve Çalışma Ruhsatı) تلقائياً.',
    dashboard_init_title: 'بدء سير العمل',
    dashboard_init_summary: 'ابدأ دردشة لإنشاء خطة التصريح الخاصة بك.',
    dashboard_init_detail: 'بمجرد وصف عملك في الدردشة ، سيقوم الذكاء الاصطناعي بإنشاء مسار تصريح مخصص لك هنا.',
    dashboard_mark_complete: 'تحديد كمكتمل',
    dashboard_mark_done: 'حدد الخطوة كمكتملة',
    dashboard_syncing: 'جاري المزامنة مع بلدية بشكتاش...',
    dashboard_toast_success: 'تم رفع المستند بنجاح!',
    status_completed: 'مكتمل',
    status_in_progress: 'قيد التنفيذ',
    status_pending: 'قيد الانتظار',
    dashboard_auto_execute: 'تشغيل البوت تلقائياً',
    chat_welcome: 'أهلاً {name}',
    chat_begin: 'من أين نبدأ؟',
    chat_placeholder_alt: 'اسأل جيميناي ٣...',
    chat_suggestion_business: 'ما هو العمل الذي تريد فتحه؟',
    chat_suggestion_permit: 'ما هو التصريح الذي تريده؟',
    chat_suggestion_location: 'أين يقع عملك؟',
    chat_suggestion_duration: 'كم من الوقت يستغرق؟',
    chat_suggestion_cost: 'كم يكلف؟',
    chat_suggestion_obtain: 'أريد الحصول على تصريح عمل',
    chat_suggestion_steps: 'أريد معرفة الخطوات',
    chat_suggestion_docs: 'ما هي الوثائق التي أحتاجها؟',
    chat_suggestion_help: 'كيف يعمل؟',
    sidebar_new_chat: 'دردشة جديدة',
    sidebar_recent: 'الأخيرة',
    sidebar_help: 'المساعدة',
    sidebar_activity: 'النشاط',
    sidebar_settings: 'الإعدادات',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'ar', 'tr'].includes(saved)) {
      setLanguage(saved);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
